version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python3.6
    steps:
      - checkout
      - run:
          python3 -m venv tutorial
          source ./tutorial/bin/activate
          pip3 install django==3.1.6
          cd django/tutorial
          python3 manage.py migrate
          python3 manage.py test

workflows:
  main:
    jobs:
      - build
