version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run: |
          python3 -m venv tutorial
          source ./tutorial/bin/activate
          pip3 install django==3.1.6
          pip3 install django-bootstrap4==2.3.1
          cd django/tutorial
          python3 manage.py migrate
          python3 manage.py test

workflows:
  main:
    jobs:
      - build
